export const KEY_LOCAL_THEME = "theme";
export const RIG_COMPONENTS = new Map([
    ['cpu', {   
        'id': 'cpu',
        'header': 'CPU',
        'selection': true,
        'name': 'AMD Ryzen 5 3600XT, 6Core & 12 Threads Unlocked Desktop Processor with Wraith Spire Cooler',
        'brand': 'AMD',
        'model': 'Ryzen 5 3600XT',
        'price': 19500,
        'qty': 1,
        'data': undefined,
    }],
    ['motherboard', {   
        'id': 'motherboard',
        'header': 'Motherboard',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['cpu_cooler', {   
        'id': 'cpu_cooler',
        'header': 'CPU Cooler',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['case', {   
        'id': 'case',
        'header': 'PC Case',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['gpu', {   
        'id': 'gpu',
        'header': 'GPU',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['ram', {   
        'id': 'ram',
        'header': 'RAM',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['storage', {   
        'id': 'storage',
        'header': 'Storage',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['case_cooler', {   
        'id': 'case_cooler',
        'header': 'Case Cooler',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['psu', {   
        'id': 'psu',
        'header': 'Power Supply',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['monitor', {   
        'id': 'monitor',
        'header': 'Monitor',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
    ['add', {   
        'id': 'add',
        'header': 'Add Component',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }],
]);