export const KEY_LOCAL_THEME = "theme";
export const PC_COMPONENTS = [
    {   
        'id': 'cpu',
        'header': 'Processor',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'motherboard',
        'header': 'Motherboard',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'cpu_cooler',
        'header': 'CPU Cooler',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'case',
        'header': 'PC Case',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'gpu',
        'header': 'Graphics Card',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'ram',
        'header': 'RAM',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'storage',
        'header': 'Storage',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'case_cooler',
        'header': 'Case Cooler',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'psu',
        'header': 'Power Supply',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'monitor',
        'header': 'Monitor',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
    {   
        'id': 'add',
        'header': 'Add Component',
        'selection': false,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'data': undefined,
    },
];