export const KEY_LOCAL_THEME = "theme";

export const RIG_COMPONENTS_NEW = {
    'cpu': {   
        'id': 'cpu',
        'header': 'CPU',
        'isSelected': false,
        'isAvailable': true,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'motherboard': {   
        'id': 'motherboard',
        'header': 'Motherboard',
        'isSelected': false,
        'isAvailable': true,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'cpu_cooler': {   
        'id': 'cpu_cooler',
        'header': 'CPU Cooler',
        'isSelected': false,
        'isAvailable': false,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'case': {   
        'id': 'case',
        'header': 'PC Case',
        'isSelected': false,
        'isAvailable': false,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'gpu': {   
        'id': 'gpu',
        'header': 'GPU',
        'isSelected': false,
        'isAvailable': true,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'ram': {   
        'id': 'ram',
        'header': 'RAM',
        'isSelected': false,
        'isAvailable': false,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'storage': {   
        'id': 'storage',
        'header': 'Storage',
        'isSelected': false,
        'isAvailable': true,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'case_cooler': {   
        'id': 'case_cooler',
        'header': 'Case Cooler',
        'isSelected': false,
        'isAvailable': false,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'psu': {   
        'id': 'psu',
        'header': 'Power Supply',
        'isSelected': false,
        'isAvailable': false,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'monitor': {   
        'id': 'monitor',
        'header': 'Monitor',
        'isSelected': false,
        'isAvailable': true,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    },
    'add': {   
        'id': 'add',
        'header': 'Add Component',
        'isSelected': false,
        'isAvailable': true,
        'image': undefined,
        'name': undefined,
        'brand': undefined,
        'model': undefined,
        'price': undefined,
        'qty': 0,
        'data': undefined,
    }
};